#!/usr/bin/env bash
#Dotfile install script

#install apple developer tools
echo "=========== Installing OSX xcode dev tools ==========="
xcode-select --install
sudo xcodebuild -license accept

#install homebrew
echo "=========== INSTALL HOMEBREW ==========="
/usr/bin/env bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

#git gotten
echo "=========== BREW BUNDLE + GIT NVIM ITERM ==========="
brew install neovim
brew install --cask kitty
brew bundle install --file=~/.dotfiles/homebrew/Brewfile

#stow the config files
stow --target $HOME zsh
stow --target $HOME nvim

echo "===========  DEFSH --> ZSH =========== "
# Change default shell to zsh
chsh -s $(which zsh)
echo "default shell changed to zsh, please re-login for changes to take effect."
