#!/usr/bin/env bash
#Dotfile install script

#install apple developer tools
echo "=========== Installing OSX xcode dev tools ==========="
xcode-select --install
sudo xcodebuild -license accept

#install homebrew
echo "=========== INSTALL HOMEBREW ==========="
/usr/bin/env bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

#git gotten
echo "=========== BREW BUNDLE + GIT NVIM ITERM ==========="
brew install git
brew install python
brew install neovim
brew install --cask iterm2
brew bundle install --file=~/.dotfiles/homebrew/Brewfile

#stow the config files
stow --target $HOME zsh
stow --target $HOME nvim

#miniconda install
wget "https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh"
bash Miniconda3-latest-MacOSX-arm64.sh
conda install -c conda-forge mamba

echo "===========  DEFSH --> ZSH =========== "
# Change default shell to zsh
chsh -s $(which zsh)
echo "default shell changed to zsh, please re-login for changes to take effect."
