return {}
-- return {
--   {
--     "stevearc/oil.nvim",
--     dependencies = { "nvim-tree/nvim-web-devicons" },
--     lazy = false,
--     config = function()
--       require("oil").setup({
--         columns = {
--           "permissions",
--           "size",
--           "mtime",
--           "icon",
--         },
--         buf_options = { buflisted = true, bufhidden = "hide" },
--         cleanup_dlay_ms = false,
--         view_options = {
--           sort = {
--             { "type", "asc" },
--             { "name", "asc" },
--           },
--         },
--       })
--     end,
--     keys = {
--       {
--         "<leader>e",
--         "<cmd>Oil<cr>",
--         desc = "Oil (file explorer)",
--       },
--     },
--   },
-- }
