return {}
-- return {
--   {
--     "mg979/vim-visual-multi",
--   },
-- {
--   "nvim-neorg/neorg",
--   build = ":Neorg sync-parsers",
--   dependencies = { "nvim-lua/plenary.nvim", "nvim-neorg/neorg-telescope" },
--   config = function()
--     require("neorg").setup({
--       load = {
--         ["core.defaults"] = {}, -- Loads default behaviour
--         ["core.concealer"] = { config = { icons = { code_block = { conceal = true } } } }, -- Adds pretty icons to your documents
--         ["core.dirman"] = { -- Manages Neorg workspaces
--           config = {
--             workspaces = {
--               school = "~/notes/school",
--               wiki = "~/notes/wiki",
--             },
--             default_workspace = "school",
--           },
--         },
--         ["core.completion"] = { config = { engine = "nvim-cmp", name = "[Neorg]" } },
--         ["core.integrations.telescope"] = {},
--         ["core.keybinds"] = {
--           config = {
--             hook = function(keybinds)
--               keybinds.remap_event("norg", "n", "<leader>nc", "core.dirman.new.note")
--               keybinds.remap_event("norg", "n", "<leader>ns", "core.integrations.telescope.find_linkable")
--               keybinds.remap_event("norg", "n", "<leader>nil", "core.integrations.telescope.insert_link")
--               -- promotion / demotion keybinds
--               keybinds.remap_event("norg", "n", "<leader>nhd", "core.promo.demote")
--               keybinds.remap_event("norg", "v", "<leader>nhd", "core.promo.demote_range")
--               keybinds.remap_event("norg", "n", "<leader>nhp", "core.promo.promote")
--               keybinds.remap_event("norg", "v", "<leader>nhd", "core.promo.promote_range")
--             end,
--           },
--         },
--       },
--     })
--   end,
--   cmd = "Neorg",
--   ft = "norg",
-- },
-- {
--   "SmiteshP/nvim-navbuddy",
--   opts = {
--     lsp = {
--       auto_attach = true,
--     },
--   },
-- },
--
--   {
--     "m4xshen/hardtime.nvim",
--     dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
--     opts = {},
--   },
-- }
--
--
-- return {
--   { "stevearc/oil.nvim", opts = {}, keys = { { "<leader>e", "<cmd>Oil<cr>", desc = "Open Parent Directory" } } },
-- }

-- return {
--   {
--     "chentoast/marks.nvim",
--     opts = {
--       default_mappings = true,
--       bookmark_0 = {
--         sign = "⚑",
--         virt_text = "hello world",
--         -- explicitly prompt for a virtual line annotation when setting a bookmark from this group.
--         -- defaults to false.
--         annotate = false,
--       },
--     },
--     -- keymaps
--     -- mx: set mark x
--     -- m,: set next available mark
--     -- m;: toggle next available mark
--     -- dmx: delete mark x
--     -- dm-: delete marks on curr line
--     -- dm<space>: delete marks in buffer
--     -- m]: next mark
--     -- m[: prev mark
--     -- m:: preview mark
--   },
-- }
--
-- return {
--   "nvim-lualine/lualine.nvim",
--   event = "VeryLazy",
--   opts = function()
--     local icons = require("lazyvim.config").icons
--     local Util = require("lazyvim.util")
--
--     local modeLetter = function()
--       local letter = vim.fn.mode()
--       return string.upper(letter)
--     end
--
--     return {
--       options = {
--         theme = "auto",
--         globalstatus = true,
--         disabled_filetypes = { statusline = { "dashboard", "alpha" } },
--       },
--       sections = {
--         lualine_a = { modeLetter },
--         lualine_b = { "branch" },
--         lualine_c = {
--           {
--             "diagnostics",
--             symbols = {
--               error = icons.diagnostics.Error,
--               warn = icons.diagnostics.Warn,
--               info = icons.diagnostics.Info,
--               hint = icons.diagnostics.Hint,
--             },
--           },
--           { "filetype", icon_only = true, separator = "", padding = { left = 1, right = 0 } },
--           { "filename", path = 0, symbols = { modified = "  ", readonly = "", unnamed = "" } },
--           -- stylua: ignore
--           {
--             function() return require("nvim-navic").get_location() end,
--             cond = function() return package.loaded["nvim-navic"] and require("nvim-navic").is_available() end,
--           },
--         },
--         lualine_x = {
--           -- stylua: ignore
--           {
--             function() return require("noice").api.status.command.get() end,
--             cond = function() return package.loaded["noice"] and require("noice").api.status.command.has() end,
--             color = Util.fg("Statement"),
--           },
--           -- stylua: ignore
--           {
--             function() return require("noice").api.status.mode.get() end,
--             cond = function() return package.loaded["noice"] and require("noice").api.status.mode.has() end,
--             color = Util.fg("Constant"),
--           },
--           -- stylua: ignore
--           {
--             function() return "  " .. require("dap").status() end,
--             cond = function () return package.loaded["dap"] and require("dap").status() ~= "" end,
--             color = Util.fg("Debug"),
--           },
--           { require("lazy.status").updates, cond = require("lazy.status").has_updates, color = Util.fg("Special") },
--           {
--             "diff",
--             symbols = {
--               added = icons.git.added,
--               modified = icons.git.modified,
--               removed = icons.git.removed,
--             },
--           },
--         },
--       },
--       extensions = { "neo-tree", "lazy" },
--     }
--   end,
-- }
--
-- return {
--   "folke/which-key.nvim",
--   opts = {
--     defaults = {
--       mode = { "n", "v" },
--       ["<leader>n"] = { name = "+neorg" },
--     },
--   },
-- }
